[package]
name = "flowsight-analysis"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Code analysis engine for FlowSight (async tracking, function pointer resolution)"

[features]
klee = []

[dependencies]
flowsight-core = { workspace = true }
flowsight-parser = { workspace = true }
flowsight-knowledge = { workspace = true }
flowsight-llvm = { workspace = true }
flowsight-index = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-c = { workspace = true }

