//! Symbolic Constraint Types
//!
//! Represents symbolic constraints generated by the symbolic executor.

use serde::{Deserialize, Serialize};
use std::fmt;

/// A symbolic constraint
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymbolicConstraint {
    /// Unique constraint ID
    pub id: String,
    /// The constraint expression
    pub expression: String,
    /// Type of constraint
    pub constraint_type: ConstraintType,
    /// The variable being constrained
    pub variable: String,
    /// Comparison operator
    pub operator: Operator,
    /// The value being compared against
    pub value: SymbolicValue,
    /// Location in source code
    pub location: Option<String>,
    /// Is this a range constraint (min, max)
    pub is_range: bool,
    /// For range constraints, the minimum value
    pub min_value: Option<SymbolicValue>,
    /// For range constraints, the maximum value
    pub max_value: Option<SymbolicValue>,
}

/// Type of symbolic constraint
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum ConstraintType {
    /// Integer comparison
    Integer,
    /// Pointer comparison (null check, etc.)
    Pointer,
    /// String comparison
    String,
    /// Array bounds check
    Bounds,
    /// Division/modulo check (division by zero)
    Division,
    /// Enum or constant comparison
    Enum,
    /// Return value check
    ReturnValue,
    /// Buffer size check
    BufferSize,
    /// Other
    Other,
}

/// Comparison operators
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum Operator {
    /// Equal ==
    Eq,
    /// Not equal !=
    Ne,
    /// Less than <
    Lt,
    /// Less than or equal <=
    Le,
    /// Greater than >
    Gt,
    /// Greater than or equal >=
    Ge,
    /// Logical AND &&
    And,
    /// Logical OR ||
    Or,
    /// Logical NOT !
    Not,
    /// In range [min, max]
    InRange,
    /// Null check (== NULL)
    IsNull,
    /// Non-null check (!= NULL)
    IsNotNull,
}

impl fmt::Display for Operator {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Operator::Eq => write!(f, "=="),
            Operator::Ne => write!(f, "!="),
            Operator::Lt => write!(f, "<"),
            Operator::Le => write!(f, "<="),
            Operator::Gt => write!(f, ">"),
            Operator::Ge => write!(f, ">="),
            Operator::And => write!(f, "&&"),
            Operator::Or => write!(f, "||"),
            Operator::Not => write!(f, "!"),
            Operator::InRange => write!(f, "in range"),
            Operator::IsNull => write!(f, "== NULL"),
            Operator::IsNotNull => write!(f, "!= NULL"),
        }
    }
}

/// A symbolic value (can be concrete or symbolic expression)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymbolicValue {
    /// The expression (e.g., "x", "x + 1", "malloc(size)")
    pub expression: String,
    /// Concrete value if known
    pub concrete: Option<String>,
    /// Type of the value
    pub type_name: String,
    /// Bit width (for integers)
    pub bit_width: Option<u32>,
    /// Is this a constant
    pub is_constant: bool,
    /// If constant, the constant value
    pub constant_value: Option<String>,
}

impl SymbolicValue {
    /// Create a new symbolic value
    pub fn new(expression: impl Into<String>, type_name: impl Into<String>) -> Self {
        Self {
            expression: expression.into(),
            concrete: None,
            type_name: type_name.into(),
            bit_width: None,
            is_constant: false,
            constant_value: None,
        }
    }

    /// Create a constant value
    pub fn constant(value: impl Into<String>, type_name: impl Into<String>) -> Self {
        let value_str = value.into();
        Self {
            expression: value_str.clone(),
            concrete: Some(value_str.clone()),
            type_name: type_name.into(),
            bit_width: None,
            is_constant: true,
            constant_value: Some(value_str),
        }
    }

    /// Create an integer constant
    pub fn int(value: i64) -> Self {
        let expr = value.to_string();
        Self {
            expression: expr.clone(),
            concrete: Some(expr.clone()),
            type_name: "int".into(),
            bit_width: Some(32),
            is_constant: true,
            constant_value: Some(expr),
        }
    }

    /// Create a pointer constant (address)
    pub fn pointer(addr: u64) -> Self {
        let expr = format!("0x{:x}", addr);
        Self {
            expression: expr.clone(),
            concrete: Some(expr.clone()),
            type_name: "void*".into(),
            bit_width: Some(64),
            is_constant: true,
            constant_value: Some(expr),
        }
    }

    /// Create a NULL pointer
    pub fn null() -> Self {
        Self {
            expression: "NULL".into(),
            concrete: Some("NULL".into()),
            type_name: "void*".into(),
            bit_width: Some(64),
            is_constant: true,
            constant_value: Some("NULL".into()),
        }
    }
}

impl fmt::Display for SymbolicValue {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if let Some(concrete) = &self.concrete {
            write!(f, "{}", concrete)
        } else {
            write!(f, "{}", self.expression)
        }
    }
}

impl SymbolicConstraint {
    /// Create a new constraint
    pub fn new(
        id: impl Into<String>,
        expression: impl Into<String>,
        variable: impl Into<String>,
        operator: Operator,
        value: SymbolicValue,
    ) -> Self {
        Self {
            id: id.into(),
            expression: expression.into(),
            constraint_type: ConstraintType::Other,
            variable: variable.into(),
            operator,
            value,
            location: None,
            is_range: false,
            min_value: None,
            max_value: None,
        }
    }

    /// Create an equality constraint
    pub fn eq(variable: impl Into<String>, value: SymbolicValue) -> Self {
        let var = variable.into();
        Self::new(
            format!("eq_{}", var),
            format!("{} == {}", var, value),
            var,
            Operator::Eq,
            value,
        )
    }

    /// Create a not-equal constraint
    pub fn ne(variable: impl Into<String>, value: SymbolicValue) -> Self {
        let var = variable.into();
        Self::new(
            format!("ne_{}", var),
            format!("{} != {}", var, value),
            var,
            Operator::Ne,
            value,
        )
    }

    /// Create a less-than constraint
    pub fn lt(variable: impl Into<String>, value: SymbolicValue) -> Self {
        let var = variable.into();
        Self::new(
            format!("lt_{}", var),
            format!("{} < {}", var, value),
            var,
            Operator::Lt,
            value,
        )
    }

    /// Create a null check constraint
    pub fn is_null(variable: impl Into<String>) -> Self {
        let var = variable.into();
        Self {
            id: format!("null_{}", var),
            expression: format!("{} == NULL", var),
            constraint_type: ConstraintType::Pointer,
            variable: var.clone(),
            operator: Operator::IsNull,
            value: SymbolicValue::null(),
            location: None,
            is_range: false,
            min_value: None,
            max_value: None,
        }
    }

    /// Create a non-null check constraint
    pub fn is_not_null(variable: impl Into<String>) -> Self {
        let var = variable.into();
        Self {
            id: format!("nonnull_{}", var),
            expression: format!("{} != NULL", var),
            constraint_type: ConstraintType::Pointer,
            variable: var.clone(),
            operator: Operator::IsNotNull,
            value: SymbolicValue::null(),
            location: None,
            is_range: false,
            min_value: None,
            max_value: None,
        }
    }

    /// Get a human-readable description
    pub fn description(&self) -> String {
        match self.operator {
            Operator::IsNull => format!("{} 必须为 NULL", self.variable),
            Operator::IsNotNull => format!("{} 不能为 NULL", self.variable),
            Operator::Eq => format!("{} 等于 {}", self.variable, self.value),
            Operator::Ne => format!("{} 不等于 {}", self.variable, self.value),
            Operator::Lt => format!("{} 小于 {}", self.variable, self.value),
            Operator::Le => format!("{} 小于等于 {}", self.variable, self.value),
            Operator::Gt => format!("{} 大于 {}", self.variable, self.value),
            Operator::Ge => format!("{} 大于等于 {}", self.variable, self.value),
            Operator::And => format!("{} 且 {}", self.variable, self.value),
            Operator::Or => format!("{} 或 {}", self.variable, self.value),
            Operator::Not => format!("非 {}", self.variable),
            Operator::InRange => {
                if let (Some(min), Some(max)) = (&self.min_value, &self.max_value) {
                    format!("{} 在 [{}, {}] 范围内", self.variable, min, max)
                } else {
                    format!("{} 在范围内", self.variable)
                }
            }
        }
    }
}

/// Collection of constraints
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConstraintSet {
    /// All constraints
    pub constraints: Vec<SymbolicConstraint>,
    /// Constraint IDs for quick lookup
    pub ids: Vec<String>,
}

impl ConstraintSet {
    /// Create an empty constraint set
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a constraint
    pub fn add(&mut self, constraint: SymbolicConstraint) {
        self.ids.push(constraint.id.clone());
        self.constraints.push(constraint);
    }

    /// Add multiple constraints
    pub fn extend(&mut self, constraints: impl IntoIterator<Item = SymbolicConstraint>) {
        for c in constraints {
            self.add(c);
        }
    }

    /// Check if empty
    pub fn is_empty(&self) -> bool {
        self.constraints.is_empty()
    }

    /// Get constraint count
    pub fn len(&self) -> usize {
        self.constraints.len()
    }

    /// Generate KLEE constraint expression
    pub fn to_klee_expression(&self) -> String {
        self.constraints
            .iter()
            .map(|c| c.expression.clone())
            .collect::<Vec<_>>()
            .join(" && ")
    }
}
